/**
 * mostly generated by chatgpt
 * @file peer.ts
 * @description
 * A self-contained peer application that:
 * - Starts a TCP server
 * - Optionally connects to another instance of itself
 * - Exchanges simple text messages
 */
import net, { Server, Socket } from "node:net"; //deno instead of node
/**
 * Peer application bootstrap (IIFE).
 *
 * @remarks
 * This self-invoking function initializes the entire peer node:
 * - Parses CLI configuration
 * - Starts the TCP server
 * - Optionally connects to a remote peer
 *
 * The function is immediately executed to avoid polluting the global scope.
 */
((): void => {
    /**
     * Represents a connected peer.
     */
    interface Peer {
        host: string;
        port: number;
        socket: Socket;
    }
    /**
     * Parsed command-line configuration.
     */
    interface PeerConfig {
        /** Port this instance listens on. */
        listenPort: number;

        /** Remote host to connect to. */
        peerHost?: string;

        /** Remote port to connect to. */
        peerPort?: number;
    }

    /**
     * Creates a configuration object from CLI arguments.
     *
     * @returns Parsed configuration.
     */
    function parseConfig(): PeerConfig {
        const listenPort: number = Number.parseInt(process.argv[2] ?? "3000", 10);
        const peerHost: string | undefined = process.argv[3];
        const peerPort: number | undefined = process.argv[4] ? Number.parseInt(process.argv[4], 10) : undefined;

        return {
            listenPort,
            peerHost,
            peerPort,
        };
    }

    /**
     * Main application configuration.
     */
    const config: PeerConfig = parseConfig();

    /**
     * Starts the TCP server.
     *
     * @param port - Port to listen on.
     * @returns The created server instance.
     */
    function createServer(port: number): Server {
        const server: Server = net.createServer(handleIncomingConnection);

        server.listen(port, () => {
            console.log(`[SERVER] Listening on port ${port}`);

            if (config.peerHost && config.peerPort) {
                connectToPeer(config.peerHost, config.peerPort);
            }
        });

        server.on("error", (error: Error) => {
            console.error(`[SERVER] Error: ${error.message}`);
        });

        return server;
    }

    /**
     * Handles a newly connected peer.
     *
     * @param socket - Connected socket.
     */
    function handleIncomingConnection(socket: Socket): void {
        const remoteAddress: string = socket.remoteAddress ?? "unknown-address";
        const remotePort: number | undefined = socket.remotePort;

        console.log(`[SERVER] Incoming connection from ${remoteAddress}:${remotePort}`);

        socket.on("data", (data: Buffer) => {
            const message: string = data.toString("utf8").trim();
            console.log(`[SERVER] Received: ${message}`);
        });

        socket.on("close", () => {
            console.log("[SERVER] Peer disconnected");
        });

        socket.on("error", (error: Error) => {
            console.error(`[SERVER] Socket error: ${error.message}`);
        });

        sendMessage(socket, `Hi from server on port ${config.listenPort}`);
    }

    /**
     * Connects to another peer instance.
     *
     * @param host - Peer hostname or IP address.
     * @param port - Peer listening port.
     */
    function connectToPeer(host: string, port: number): void {
        const client: Socket = net.createConnection({ host, port }, () => {
            console.log(`[CLIENT] Connected to peer ${host}:${port}`);
            sendMessage(client, `Hi from peer on port ${config.listenPort}`);
        });

        client.on("data", (data: Buffer) => {
            const message: string = data.toString("utf8").trim();
            console.log(`[CLIENT] Received: ${message}`);
        });

        client.on("close", () => {
            console.log("[CLIENT] Connection closed");
        });

        client.on("error", (error: Error) => {
            console.error(`[CLIENT] Connection error: ${error.message}`);
        });
    }

    /**
     * Sends a text message through a socket.
     *
     * @param socket - Destination socket.
     * @param message - Message to send.
     */
    function sendMessage(socket: Socket, message: string): void {
        socket.write(`${message}\n`);
    }

    /**
     * Application entry point.
     */
    function main(): void {
        createServer(config.listenPort);
    }

    main();
})();